/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MockTestContent = IDL.Variant({
  'pdf' : IDL.Text,
  'video' : IDL.Text,
  'text' : IDL.Text,
});
export const Time = IDL.Int;
export const PopupAnnouncement = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'audioUrl' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const SiteWideEffect = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'createdAt' : Time,
  'description' : IDL.Text,
  'effectType' : IDL.Text,
  'triggerEpisode' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Centre = IDL.Record({
  'id' : IDL.Text,
  'phoneNumbers' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
});
export const EmbedConfig = IDL.Record({
  'announcementVideoEmbedUrl' : IDL.Opt(IDL.Text),
  'youtubeIntroUrl' : IDL.Text,
  'youtubeFacebookPageUrl' : IDL.Text,
});
export const MockTest = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : MockTestContent,
  'createdAt' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateCentre' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'adminToggleEffectActive' : IDL.Func([IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearSiteWideEffect' : IDL.Func([], [], []),
  'createAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createMockTest' : IDL.Func([IDL.Text, MockTestContent], [IDL.Nat], []),
  'createOrUpdatePopupAnnouncement' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'deactivatePopupAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteCentre' : IDL.Func([IDL.Text], [], []),
  'deleteMockTest' : IDL.Func([IDL.Nat], [], []),
  'deletePopupAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'getActivePopupAnnouncements' : IDL.Func(
      [],
      [IDL.Vec(PopupAnnouncement)],
      ['query'],
    ),
  'getActiveSiteWideEffect' : IDL.Func(
      [],
      [IDL.Opt(SiteWideEffect)],
      ['query'],
    ),
  'getAllPopupsSorted' : IDL.Func([], [IDL.Vec(PopupAnnouncement)], ['query']),
  'getAllPopupsSortedById' : IDL.Func(
      [],
      [IDL.Vec(PopupAnnouncement)],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCentres' : IDL.Func([], [IDL.Vec(Centre)], ['query']),
  'getEmbedConfig' : IDL.Func([], [EmbedConfig], ['query']),
  'getMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
  'getMockTestsByType' : IDL.Func([IDL.Text], [IDL.Vec(MockTest)], ['query']),
  'getPopupAnnouncementById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PopupAnnouncement)],
      ['query'],
    ),
  'getPopupsPaged' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'hasNextPage' : IDL.Bool,
          'popups' : IDL.Vec(PopupAnnouncement),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEffectActive' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'revokeAdminAccess' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'triggerSiteWideEffect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'unlockAdminAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateEmbedConfig' : IDL.Func([EmbedConfig], [], []),
  'updateMockTest' : IDL.Func([IDL.Nat, IDL.Text, MockTestContent], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MockTestContent = IDL.Variant({
    'pdf' : IDL.Text,
    'video' : IDL.Text,
    'text' : IDL.Text,
  });
  const Time = IDL.Int;
  const PopupAnnouncement = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'audioUrl' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const SiteWideEffect = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'createdAt' : Time,
    'description' : IDL.Text,
    'effectType' : IDL.Text,
    'triggerEpisode' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Centre = IDL.Record({
    'id' : IDL.Text,
    'phoneNumbers' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
  });
  const EmbedConfig = IDL.Record({
    'announcementVideoEmbedUrl' : IDL.Opt(IDL.Text),
    'youtubeIntroUrl' : IDL.Text,
    'youtubeFacebookPageUrl' : IDL.Text,
  });
  const MockTest = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : MockTestContent,
    'createdAt' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateCentre' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminToggleEffectActive' : IDL.Func([IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearSiteWideEffect' : IDL.Func([], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createMockTest' : IDL.Func([IDL.Text, MockTestContent], [IDL.Nat], []),
    'createOrUpdatePopupAnnouncement' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'deactivatePopupAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteCentre' : IDL.Func([IDL.Text], [], []),
    'deleteMockTest' : IDL.Func([IDL.Nat], [], []),
    'deletePopupAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'getActivePopupAnnouncements' : IDL.Func(
        [],
        [IDL.Vec(PopupAnnouncement)],
        ['query'],
      ),
    'getActiveSiteWideEffect' : IDL.Func(
        [],
        [IDL.Opt(SiteWideEffect)],
        ['query'],
      ),
    'getAllPopupsSorted' : IDL.Func(
        [],
        [IDL.Vec(PopupAnnouncement)],
        ['query'],
      ),
    'getAllPopupsSortedById' : IDL.Func(
        [],
        [IDL.Vec(PopupAnnouncement)],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCentres' : IDL.Func([], [IDL.Vec(Centre)], ['query']),
    'getEmbedConfig' : IDL.Func([], [EmbedConfig], ['query']),
    'getMockTests' : IDL.Func([], [IDL.Vec(MockTest)], ['query']),
    'getMockTestsByType' : IDL.Func([IDL.Text], [IDL.Vec(MockTest)], ['query']),
    'getPopupAnnouncementById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PopupAnnouncement)],
        ['query'],
      ),
    'getPopupsPaged' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'hasNextPage' : IDL.Bool,
            'popups' : IDL.Vec(PopupAnnouncement),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEffectActive' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'revokeAdminAccess' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'triggerSiteWideEffect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'unlockAdminAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateEmbedConfig' : IDL.Func([EmbedConfig], [], []),
    'updateMockTest' : IDL.Func([IDL.Nat, IDL.Text, MockTestContent], [], []),
  });
};

export const init = ({ IDL }) => { return []; };