/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
  'audioUrl' : [] | [string],
  'videoUrl' : [] | [string],
}
export interface Centre {
  'id' : string,
  'phoneNumbers' : Array<string>,
  'name' : string,
  'address' : [] | [string],
}
export interface EmbedConfig {
  'announcementVideoEmbedUrl' : [] | [string],
  'youtubeIntroUrl' : string,
  'youtubeFacebookPageUrl' : string,
}
export interface MockTest {
  'id' : bigint,
  'title' : string,
  'content' : MockTestContent,
  'createdAt' : Time,
}
export type MockTestContent = { 'pdf' : string } |
  { 'video' : string } |
  { 'text' : string };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateCentre' : ActorMethod<
    [string, string, Array<string>, [] | [string]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<
    [string, [] | [string], [] | [string]],
    bigint
  >,
  'createMockTest' : ActorMethod<[string, MockTestContent], bigint>,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteCentre' : ActorMethod<[string], undefined>,
  'deleteMockTest' : ActorMethod<[bigint], undefined>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCentres' : ActorMethod<[], Array<Centre>>,
  'getEmbedConfig' : ActorMethod<[], EmbedConfig>,
  'getMockTests' : ActorMethod<[], Array<MockTest>>,
  'getMockTestsByType' : ActorMethod<[string], Array<MockTest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAnnouncement' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    undefined
  >,
  'updateEmbedConfig' : ActorMethod<[EmbedConfig], undefined>,
  'updateMockTest' : ActorMethod<[bigint, string, MockTestContent], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];