/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MockTest {
    id: bigint;
    title: string;
    content: MockTestContent;
    createdAt: Time;
}
export type Time = bigint;
export type MockTestContent = {
    __kind__: "pdf";
    pdf: string;
} | {
    __kind__: "video";
    video: string;
} | {
    __kind__: "text";
    text: string;
};
export interface Announcement {
    id: bigint;
    createdAt: Time;
    text: string;
    audioUrl?: string;
    videoUrl?: string;
}
export interface Centre {
    id: string;
    phoneNumbers: Array<string>;
    name: string;
    address?: string;
}
export interface UserProfile {
    name: string;
}
export interface EmbedConfig {
    announcementVideoEmbedUrl?: string;
    youtubeIntroUrl: string;
    youtubeFacebookPageUrl: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addOrUpdateCentre(id: string, name: string, phoneNumbers: Array<string>, address: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAnnouncement(text: string, videoUrl: string | null, audioUrl: string | null): Promise<bigint>;
    createMockTest(title: string, content: MockTestContent): Promise<bigint>;
    deleteAnnouncement(id: bigint): Promise<void>;
    deleteCentre(id: string): Promise<void>;
    deleteMockTest(id: bigint): Promise<void>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCentres(): Promise<Array<Centre>>;
    getEmbedConfig(): Promise<EmbedConfig>;
    getMockTests(): Promise<Array<MockTest>>;
    getMockTestsByType(contentType: string): Promise<Array<MockTest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateAnnouncement(id: bigint, text: string, videoUrl: string | null, audioUrl: string | null): Promise<void>;
    updateEmbedConfig(config: EmbedConfig): Promise<void>;
    updateMockTest(id: bigint, title: string, content: MockTestContent): Promise<void>;
}
import type { Announcement as _Announcement, Centre as _Centre, EmbedConfig as _EmbedConfig, MockTest as _MockTest, MockTestContent as _MockTestContent, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addOrUpdateCentre(arg0: string, arg1: string, arg2: Array<string>, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrUpdateCentre(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrUpdateCentre(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAnnouncement(arg0: string, arg1: string | null, arg2: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnnouncement(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnnouncement(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createMockTest(arg0: string, arg1: MockTestContent): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMockTest(arg0, to_candid_MockTestContent_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMockTest(arg0, to_candid_MockTestContent_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAnnouncement(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAnnouncement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAnnouncement(arg0);
            return result;
        }
    }
    async deleteCentre(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCentre(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCentre(arg0);
            return result;
        }
    }
    async deleteMockTest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMockTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMockTest(arg0);
            return result;
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCentres(): Promise<Array<Centre>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCentres();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCentres();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmbedConfig(): Promise<EmbedConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmbedConfig();
                return from_candid_EmbedConfig_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmbedConfig();
            return from_candid_EmbedConfig_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTests(): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTests();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTests();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMockTestsByType(arg0: string): Promise<Array<MockTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMockTestsByType(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMockTestsByType(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateAnnouncement(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAnnouncement(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAnnouncement(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateEmbedConfig(arg0: EmbedConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmbedConfig(to_candid_EmbedConfig_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmbedConfig(to_candid_EmbedConfig_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMockTest(arg0: bigint, arg1: string, arg2: MockTestContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMockTest(arg0, arg1, to_candid_MockTestContent_n4(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMockTest(arg0, arg1, to_candid_MockTestContent_n4(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_Announcement_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Centre_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Centre): Centre {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EmbedConfig_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmbedConfig): EmbedConfig {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MockTestContent_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTestContent): MockTestContent {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MockTest_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MockTest): MockTest {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    phoneNumbers: Array<string>;
    name: string;
    address: [] | [string];
}): {
    id: string;
    phoneNumbers: Array<string>;
    name: string;
    address?: string;
} {
    return {
        id: value.id,
        phoneNumbers: value.phoneNumbers,
        name: value.name,
        address: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.address))
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    announcementVideoEmbedUrl: [] | [string];
    youtubeIntroUrl: string;
    youtubeFacebookPageUrl: string;
}): {
    announcementVideoEmbedUrl?: string;
    youtubeIntroUrl: string;
    youtubeFacebookPageUrl: string;
} {
    return {
        announcementVideoEmbedUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.announcementVideoEmbedUrl)),
        youtubeIntroUrl: value.youtubeIntroUrl,
        youtubeFacebookPageUrl: value.youtubeFacebookPageUrl
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: _MockTestContent;
    createdAt: _Time;
}): {
    id: bigint;
    title: string;
    content: MockTestContent;
    createdAt: Time;
} {
    return {
        id: value.id,
        title: value.title,
        content: from_candid_MockTestContent_n21(_uploadFile, _downloadFile, value.content),
        createdAt: value.createdAt
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    createdAt: _Time;
    text: string;
    audioUrl: [] | [string];
    videoUrl: [] | [string];
}): {
    id: bigint;
    createdAt: Time;
    text: string;
    audioUrl?: string;
    videoUrl?: string;
} {
    return {
        id: value.id,
        createdAt: value.createdAt,
        text: value.text,
        audioUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.audioUrl)),
        videoUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: string;
} | {
    video: string;
} | {
    text: string;
}): {
    __kind__: "pdf";
    pdf: string;
} | {
    __kind__: "video";
    video: string;
} | {
    __kind__: "text";
    text: string;
} {
    return "pdf" in value ? {
        __kind__: "pdf",
        pdf: value.pdf
    } : "video" in value ? {
        __kind__: "video",
        video: value.video
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Centre>): Array<Centre> {
    return value.map((x)=>from_candid_Centre_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MockTest>): Array<MockTest> {
    return value.map((x)=>from_candid_MockTest_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n7(_uploadFile, _downloadFile, x));
}
function to_candid_EmbedConfig_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmbedConfig): _EmbedConfig {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_MockTestContent_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MockTestContent): _MockTestContent {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    announcementVideoEmbedUrl?: string;
    youtubeIntroUrl: string;
    youtubeFacebookPageUrl: string;
}): {
    announcementVideoEmbedUrl: [] | [string];
    youtubeIntroUrl: string;
    youtubeFacebookPageUrl: string;
} {
    return {
        announcementVideoEmbedUrl: value.announcementVideoEmbedUrl ? candid_some(value.announcementVideoEmbedUrl) : candid_none(),
        youtubeIntroUrl: value.youtubeIntroUrl,
        youtubeFacebookPageUrl: value.youtubeFacebookPageUrl
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "pdf";
    pdf: string;
} | {
    __kind__: "video";
    video: string;
} | {
    __kind__: "text";
    text: string;
}): {
    pdf: string;
} | {
    video: string;
} | {
    text: string;
} {
    return value.__kind__ === "pdf" ? {
        pdf: value.pdf
    } : value.__kind__ === "video" ? {
        video: value.video
    } : value.__kind__ === "text" ? {
        text: value.text
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
